### ISSUE TITLE
Separate RPM API

### ISSUE THREAD

**Issue by ruckc** [ctron/rpm-builder#1]
Can you separate the RPM API into a separate jar?  It would be extremely beneficial for a single RPM API, as this project is more focused on the building of RPMs, and packagedrone's copy is more focused on extracting metadata from RPMs.

I'm working on a pure-Java yum repodata generator, and I don't like that I have to keep copying packages out of other repositories to dependency free access to them.... It doesn't let me easily write something using your amazing RPM APIs, and I honestly don't want to maintain a fork that has no git log ties to yours.

**Comment by ctron** [comment]
This is definitely on the road map. It will be available when the final release is made. In a few weeks.

**Comment by ctron** [comment]
There already is a yum repository generator in package drone. It could be separated as well. You might want to o have a look at it: https://github.com/eclipse/packagedrone/blob/master/bundles/org.eclipse.packagedrone.repo.adapter.rpm/src/org/eclipse/packagedrone/repo/adapter/rpm/yum/RepositoryCreator.java

**Comment by ruckc** [comment]
I needed the ability to read and write local and remote repodata manifests, so my API is JAXB based, and I'm slowly working through the JAXB inconsistencies with xmlunit.

I needed a much more expansive API around a generic Repository object, with the ability to dynamically add/remove packages, inspect dependencies and package contents, and regenerate the metadata automatically inside a repository framework.

**Comment by ctron** [comment]
So if you don't mind using a SNAPSHOT version for a while, then you can use this [1]

[1] https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/packagedrone/org.eclipe.packagedrone.utils.rpm/0.13.0-SNAPSHOT/

**Comment by ctron** [comment]
Its published: https://search.maven.org/#artifactdetails|org.eclipse.packagedrone|org.eclipse.packagedrone.utils.rpm|0.13.0|jar

```
<dependency>
    <groupId>org.eclipse.packagedrone</groupId>
    <artifactId>org.eclipse.packagedrone.utils.rpm</artifactId>
    <version>0.13.0</version>
</dependency>
```
