### ISSUE TITLE
Install produced RPM file into Maven repository

### ISSUE THREAD

**Issue by vsinkievic** [ctron/rpm-builder#15]
At the moment produced RPM file is not installed into Maven repository or Artifactory. 
I tried to add maven config into pom file but it fails, because I need to know exactly file name of the artifact and ${project.version} is not equal to the RPM version.

How it is possible to deploy RPM to Artifactory?
How to access filename of RPM file in the POM?

Below is configuration I tried to use to install RPM file:

> 			<plugin>
> 				<groupId>org.apache.maven.plugins</groupId>
> 				<artifactId>maven-install-plugin</artifactId>
> 				<executions>
> 					<execution>
> 						<phase>install</phase>
> 						<goals>
> 							<goal>install-file</goal>
> 						</goals>
> 						<configuration>
> 							<packaging>rpm</packaging>
> 							<artifactId>${project.artifactId}</artifactId>
> 							<groupId>${project.groupId}</groupId>
> 							<version>${project.version}</version>
> 							<file>
> 								${project.build.directory}/${project.artifactId}-${project.version}-noarch.rpm
> 							</file>
> 						</configuration>
> 					</execution>
> 				</executions>
> 			</plugin>

**Comment by ctron** [comment]
By default the result artifact will be "attached" to the build, which should allow an immediate upload using simple `mvn deploy` or `mvn install` for the local repository. Also see: https://ctron.github.io/rpm-builder/rpm-mojo.html#attach

**Comment by vsinkievic** [comment]
But it deploys jar and pom files only. RPM is not deployed. I tested this with local Maven repository and Artifactory (using version 0.9.2)

**Comment by ctron** [comment]
It works for me. Could you make an example project and that share that?

**Comment by vsinkievic** [comment]
> <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
> 	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
> 	<modelVersion>4.0.0</modelVersion>
> 
> 	<groupId>.....</groupId>
> 	<artifactId>.....</artifactId>
> 	<version>1.0.1-SNAPSHOT</version>
> 	<packaging>jar</packaging>
> 
> 	<name>.....</name>
> 	<description>......</description>
> 
> 	<properties>
> 		<pas-service-version>0.2.0</pas-service-version>
> 		<dobu-version>1.0.6</dobu-version>
> 		<camel-version>2.18.3</camel-version>
> 		<jetty.version>9.2.19.v20160908</jetty.version>
> 		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
> 		<java.version>1.8</java.version>
> 		<maven.compiler.source>${java.version}</maven.compiler.source>
> 		<maven.compiler.target>${java.version}</maven.compiler.target>
> 		<install-directory>/opt/${project.name}</install-directory>
> 	</properties>
> 
> 	<parent>
> 		<groupId>org.springframework.boot</groupId>
> 		<artifactId>spring-boot-starter-parent</artifactId>
> 		<version>1.5.3.RELEASE</version>
> 		<relativePath /> 
> 	</parent>
> 
> 
> 	<dependencies>
> 		<dependency>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-starter-actuator</artifactId>
> 		</dependency>
> 
> 		<dependency>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-starter-test</artifactId>
> 			<scope>test</scope>
> 		</dependency>
> 
> 		<dependency>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-starter-logging</artifactId>
> 		</dependency>
> 
> 		<dependency>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-starter-web</artifactId>
> 			<exclusions>
> 				<exclusion>
> 					<groupId>org.springframework.boot</groupId>
> 					<artifactId>spring-boot-starter-tomcat</artifactId>
> 				</exclusion>
> 			</exclusions>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-starter-jetty</artifactId>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-starter-websocket</artifactId>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-starter-security</artifactId>
> 		</dependency>
> 		<dependency>
> 			<groupId>javax.inject</groupId>
> 			<artifactId>javax.inject</artifactId>
> 			<version>1</version>
> 		</dependency>
> 
> 
> 		<dependency>
> 			<groupId>....</groupId>
> 			<artifactId>dobu</artifactId>
> 			<version>${dobu-version}</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>....</groupId>
> 			<artifactId>pas-datatypes</artifactId>
> 			<version>${pas-service-version}</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>....</groupId>
> 			<artifactId>pas-service</artifactId>
> 			<version>${pas-service-version}</version>
> 		</dependency>
> 
> 
> 		<dependency>
> 			<groupId>org.apache.camel</groupId>
> 			<artifactId>camel-spring-boot-starter</artifactId>
> 			<version>${camel-version}</version>
> 		</dependency>
> 
> 		<dependency>
> 			<groupId>org.apache.camel</groupId>
> 			<artifactId>camel-mail</artifactId>
> 			<version>${camel-version}</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.apache.camel</groupId>
> 			<artifactId>camel-exec</artifactId>
> 			<version>${camel-version}</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.apache.camel</groupId>
> 			<artifactId>camel-quartz</artifactId>
> 			<version>${camel-version}</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.apache.camel</groupId>
> 			<artifactId>camel-jaxb</artifactId>
> 			<version>${camel-version}</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.apache.camel</groupId>
> 			<artifactId>camel-jsch</artifactId>
> 			<version>${camel-version}</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.apache.camel</groupId>
> 			<artifactId>camel-ftp</artifactId>
> 			<version>${camel-version}</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.apache.camel</groupId>
> 			<artifactId>camel-atmosphere-websocket</artifactId>
> 			<version>${camel-version}</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.apache.camel</groupId>
> 			<artifactId>camel-stomp</artifactId>
> 			<version>${camel-version}</version>
> 		</dependency>
> 
> 
> 		<dependency>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-devtools</artifactId>
> 		</dependency>
> 	</dependencies>
> 
> 	<build>
> 		<plugins>
> 			<plugin>
> 				<groupId>com.ning.maven.plugins</groupId>
> 				<artifactId>maven-duplicate-finder-plugin</artifactId>
> 				<version>1.0.8</version>
> 			</plugin>
> 			<plugin>
> 				<groupId>org.springframework.boot</groupId>
> 				<artifactId>spring-boot-maven-plugin</artifactId>
> 				<configuration>
> 					<mainClass>org.apache.camel.spring.boot.FatJarRouter</mainClass>
> 					<executable>true</executable>
> 				</configuration>
> 				<executions>
> 					<execution>
> 						<goals>
> 							<goal>repackage</goal>
> 						</goals>
> 					</execution>
> 				</executions>
> 			</plugin>
> 			<plugin>
> 				<groupId>de.dentrassi.maven</groupId>
> 				<artifactId>rpm</artifactId>
> 				<version>0.9.2</version>
> 				<executions>
> 					<execution>
> 						<id>build-rpm</id>
> 						<phase>verify</phase>
> 						<goals>
> 							<goal>rpm</goal>
> 						</goals>
> 						<inherited>false</inherited>
> 						<configuration>
> 							<attach>false</attach>
> 							<group>Application/Misc</group>
> 						</configuration>
> 					</execution>
> 				</executions>
> 				<configuration>
> 					<skipSigning>true</skipSigning>
> 					<beforeInstallation>
> 						<script>
> 						</script>
> 					</beforeInstallation>
> 					<afterInstallation>
.> 					</afterInstallation>
> 					<afterRemoval>
> 						systemctl daemon-reload
> 					</afterRemoval>
> 					<entries>
> 						<entry>
> 							<name>${install-directory}</name>
> 							<directory>true</directory>
.> 							<mode>0775</mode>
> 						</entry>
> 						<entry>
> 							<name>${install-directory}/routes</name>
> 							<directory>true</directory>
.> 							<mode>0775</mode>
> 						</entry>
> 						<entry>
> 							<name>${install-directory}/test_route</name>
> 							<directory>true</directory>
.> 							<mode>0775</mode>
> 						</entry>
> 						<entry>
> 							<name>${install-directory}/test_route/in</name>
> 							<directory>true</directory>
.> 							<mode>0775</mode>
> 						</entry>
> 						<entry>
> 							<name>${install-directory}/test_route/out</name>
> 							<directory>true</directory>
.> 							<mode>0775</mode>
> 						</entry>
> 						<entry>
> 							<name>${install-directory}/${project.build.finalName}.jar</name>
> 							<collect>
> 								<from>target/${project.build.finalName}.jar</from>
> 							</collect>
.> 							<mode>0644</mode>
> 						</entry>
> 						<entry>
> 							<name>${install-directory}/application.properties</name>
> 							<collect>
> 								<from>src/main/resources/application.properties</from>
> 							</collect>
.> 							<mode>0644</mode>
> 						</entry>
> 						<entry>
> 							<name>${install-directory}/readme.txt</name>
> 							<collect>
> 								<from>src/main/resources/readme.txt</from>
> 							</collect>
.> 							<mode>0644</mode>
> 						</entry>
> 						<entry>
> 							<name>${install-directory}/myfile.jar</name>
> 							<linkTo>${install-directory}/${project.build.finalName}.jar</linkTo>
> 						</entry>
> 					</entries>
> 				</configuration>
> 			</plugin>
>  			<plugin>
> 				<artifactId>maven-release-plugin</artifactId>
> 				<version>2.5.3</version>
> 			</plugin>
> 		</plugins>
> 	</build>
> </project>

**Comment by ctron** [comment]
So why are you setting `<attach>false</attach>` when you want to actually attach your RPM file?

**Comment by vsinkievic** [comment]
Its my fault! I copied config from somewhere and didn't analyze it too much...

Thank you!

**Comment by ctron** [comment]
No problem.
