### ISSUE TITLE
Specify name of rpm package

### ISSUE THREAD

**Issue by madoar** [ctron/rpm-builder#16]
Is there a way to manually specify the name of the created rpm package?
As fas as I understand your example you're using the `name` property inside the pom.xml file by default, I think it would be useful to specify the package name manually.
I'm not using rpm myself, but debian. On debian I've discovered that package names containing ` ` (spaces) are bad. Is this true for rpm packages too, if yes does the plugin cover that?

**Comment by ctron** [comment]
Did you check: https://ctron.github.io/rpm-builder/rpm-mojo.html#packageName

TBH, I am not sure if RPM allows that. The rpm-builder leaves the name nearly as specified: [RpmMojo.java:740](https://github.com/ctron/rpm-builder/blob/bb3a5e1d0693073c4ad74425013ca03b3a181f06/src/main/java/de/dentrassi/rpm/builder/RpmMojo.java#L740)

It currently only does a trim, aside from the legacy handling of the package name.

**Comment by madoar** [comment]
Thanks for the first link to the documentation. I haven't found a link to the parameters before (it's kind of strange in my opinion to use the goals as an anchor for the parameters).

About the package name preprocessing:
I think it would be best to either give an error to the user, if the name is illegal, or to fix it, e.g. replace all illegal characters by something else.

**Comment by ctron** [comment]
I agree ... the question now is: what is illegal 😉

**Comment by madoar** [comment]
After a little searching on google, I've found https://fedoraproject.org/wiki/Packaging:Naming?rd=Packaging:NamingGuidelines. I'm not sure how official this is, but I think it could be used as a first step.

**Comment by ctron** [comment]
I am aware of those. And they actually are the whole mess with the lowercase handling in previous versions.

Those are suggestions, for Fedora. However RPM doesn't have those rules/limitations. So if people decide to do it differently, then just let them.

**Comment by ctron** [comment]
I think we can close this one as the package name can be specified using the property `packageName`: https://ctron.github.io/rpm-builder/rpm-mojo.html#packageName
