### ISSUE TITLE
Provide a way to override the rpm release number suffix for snapshot builds.

### ISSUE THREAD

**Issue by ProggerPete** [ctron/rpm-builder#2]
The plugin currently provides a way to override the rpm release number for release builds by specifying the 'release' parameter.

For snapshot builds you can override the rpm release prefix with the 'snapshotReleasePrefix' parameter.

However there is no way to override the rpm release suffix. In my case I would like to set a 'snapshotReleaseSuffix' parameter and make it equal to the build number from our automated build system. (Instead of the default timestamp suffix.)

That way I can easily reference the rpm I've just built in later build steps.

**Comment by ProggerPete** [comment]
It occurs to me that just allowing the release argument to override snapshot release number if it's defined is probably even better.

i.e. if the 'release' parameter is specified then always use it, otherwise do your current automatic stuff.

**Comment by ctron** [comment]
Ok, understood. I will look into this. Hopefully today.

**Comment by ctron** [comment]
So letting the release property always override it works a bit against the initial idea. Which was to be able to configure the while thing in a top level project and then let it decide on its own wether it is a snapshot build or not and then automatically attach a build id (currently fixed the current time). But constructing a release string which is "0.*" for all snapshots and "1" it this is not a release build.

I do understand that for snpashot builds you don't want to rely on the automatic generated timestamp. And I do understand that. So my proposal would be to define a `snapshotBuildTimestamp` which defaults to the current format, but only gets picked when it is a snapshot build.

Would that work for you?

**Comment by ctron** [comment]
I did add a `forceRelease` parameter in addition, so that it is possible to disable the snapshot mechanism altogether and always use the value of the `release` parameter.

**Comment by ctron** [comment]
The change is pushed to Maven Central as version 0.6.0. But you need to wait a bit until it gets actually synced to Maven Central.

**Comment by ctron** [comment]
It is synced: https://repo1.maven.org/maven2/de/dentrassi/maven/rpm/0.6.0/

**Comment by ProggerPete** [comment]
Both snapshotBuildTimestamp and the forceRelease parameters sound like they'll do the trick for me. Top work. =)
