### ISSUE TITLE
Missing  Recommends and Suggests dependencies

### ISSUE THREAD

**Issue by Sami32** [ctron/rpm-builder#27]
http://rpm.org/user_doc/boolean_dependencies.html

I don't know if it is a shared opinion, but i find Recommends dependency useful for automatically download the enhancement libraries need for the project after the user approval.
That make things much easy for the users while still leaving the user choice approval choice.

I see the Suggests dependency as useful when users don't read your Wiki or other documentation, and since they often just run it...
At least this way they have the advices under their eyes at install time.

**Comment by Sami32** [comment]
BTW, i know that we sadly always miss that point, but thank you for that great peace of work 👍 
I was happy to modify my code to use your artifact instead of the rpm-maven-plugin one 😉

**Comment by ctron** [comment]
This should be fixed in version 1.0.0 which I just released. Please re-open otherwise.
