### ISSUE TITLE
Entryset Collect not excluding directories

### ISSUE THREAD

**Issue by Ajbawa** [ctron/rpm-builder#3]
Given the following entry:

```XML
<entry>
    <name>${my-deploy.dir}</name>
    <collect>
      <from>../rpm-module-a/target/</from>
      <directories>false</directories>
    </collect>
    <user>jboss1</user>
    <group>jboss1</group>
    <mode>0640</mode>
</entry>
```

I find directories from the `../rpm-module-a/target/` are still included in the .rpm archive. 
How is one supposed to exclude directories and / or filter files included using a 'collect'.

I am using version 0.8.0 of the plugin and currently have no `rulesets` defined in the pom.xml.

**Comment by ctron** [comment]
Do you have an example?

Currently there is no way to exclude files from a "collect" entry.

**Comment by Ajbawa** [comment]
I am not concerned with excluding / filtering files - its a nice to have. 
Something like '<from>../rpm-module-a/target/**.jar</from>'  to only collect .jar files.

What I really need is to exclude any sub-folders in the `<from>../rpm-module-a/target/</from>` folder ?
I was under the impression that was the purpose of `<directories>false</directories>` option ?

**Comment by ctron** [comment]
The directories flag controls whether directories are marked as directories. Meaning that the RPM will "own" that directory and remove it during removal of the RPM.

**Comment by Ajbawa** [comment]
Thanks - I now understand its purpose.
I do need to understand the RPM format much better. I have been able to work around my issues by add a single file. 
This issue is no longer valid and I will close it. 
Thanks for your prompt responses.

**Comment by ctron** [comment]
Thanks for reporting!
