### ISSUE TITLE
CreateRepo detects Source RPM due to missing Source RPM Header

### ISSUE THREAD

**Issue by DevFlorian** [ctron/rpm-builder#30]
rpms doesn't work with zypper or createRepo.
Maybe add a default Entry for Source RPM Header like gradle RPM Plugin does.

// need a source package because createrepo will assume your package is a source package without it

https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/master/src/main/groovy/com/netflix/gradle/plugins/rpm/RpmCopyAction.groovy

**Comment by ctron** [comment]
Which version of the plugin do you use? There was a bug in the 0.9.x versions which made "yum" detect RPMs are source RPMs although they were not. This should be fixes in 0.10.x releases.

From the link you provide I am not really sure what you are pointing to.

Maybe you could also add a bit more context of what is not working. Like something to reproduce.

**Comment by DevFlorian** [comment]
I'm using 0.10.2 and createrepo to create a repomd.xml.
This is my configuration:
`<skipSigning>true</skipSigning>
<attach>false</attach>
<group>default</group>
<release>${project.version}</release>
<architecture>x86_64</architecture>
<vendor>vendor</vendor>
<operatingSystem>LINUX</operatingSystem>
<leadOverrideArchitecture>AARCH64</leadOverrideArchitecture>`

In my repomd.xml it says <arch>src</arch>.
The gradle Plugin sets something as Source RPM Header to prevent this.

if (!sourcePackage) {
            // need a source package because createrepo will assume your package is a source package without it
            sourcePackage = builder.defaultSourcePackage
}

**Comment by ctron** [comment]
Ok I see … thanks for the update. I guess that could be a quick fix.

**Comment by ctron** [comment]
This should be fixed in version 1.0.0 which I just released. Please re-open otherwise.
