### ISSUE TITLE
Failed to execute goal de.dentrassi.maven:rpm:0.10.2:rpm (default) on project cfi: 'keyId' parameter not set:

### ISSUE THREAD

**Issue by MkJha** [ctron/rpm-builder#32]
Failed to execute goal de.dentrassi.maven:rpm:0.10.2:rpm (default) on project cfi: 'keyId' parameter not set: 'keyId' parameter not set:
[ERROR] Signing requires the 'keyId' to the user id of the GPG key to use.

Could you please help me to get rid of this ?

**Comment by ctron** [comment]
Looks like you want to sign but did not set a key id to sign. Maybe have a look at the documentation: https://ctron.github.io/rpm-builder/signing.html
