### ISSUE TITLE
add plugin-specific skip parameter

### ISSUE THREAD

**Issue by glebsts** [ctron/rpm-builder#35]
Hello,
Can we have `-Dskip.rpm` (or similar) parameter and XML config parameter for just skipping RPM build?
Useful for int.tests building where I don't need to have RPM.

Right now I run `mvn verify -Dmaven.test.skip -Dskip.npm -Dskip.webpack` (skipping non-needed UI packing and unit tests) but I cannot skip RPM. Playing around profile-specific plugin configuration makes pom much less readable.
Thank you.

**Comment by ctron** [comment]
Absolutely!

**Comment by ctron** [comment]
I released 1.1.1, which should fix this issue.

**Comment by glebsts** [comment]
Thank you very much for this quick update.
Just a note for everyone interested, that release comments say `skip.rpm`, `skip.yum`, but actual CLI argument is `-Drpm.skip`, `-Dyum.skip` according to my experiments.

**Comment by ctron** [comment]
Indeed, thanks for letting me know. I fixed the release comment.
