### ISSUE TITLE
Possibility to define Relocations

### ISSUE THREAD

**Issue by skarzhevskyy** [ctron/rpm-builder#4]
Is it possible to define Relocation Prefixes so PRM can be installed to user select directories?

**Comment by ctron** [comment]
Not right now. Since I haven't figured out how this is represented in the RPM files, I am not sure how difficult that will be.

But I am happy to help with that.

**Comment by syedimty** [comment]
@ctron Any update to this issue. I am looking to make a relocatable package, unable figure out how. Success migrated my project to this, except for this one thing.

**Comment by ctron** [comment]
Sorry, not at the moment. Again, I am happy to help with contributions.
