### ISSUE TITLE
Required Class ZstdUtils not found

### ISSUE THREAD

**Issue by IT-Berater** [ctron/rpm-builder#45]
Hi,
Version 1.2. works fine. Update to 1.3 on Win10 throw this Exception:

`[ERROR] Failed to execute goal de.dentrassi.maven:rpm:1.3.0:rpm (default) on project ee_server_rpm_konfig_test: Execution default of goal de.dentrassi.maven:rpm:1.3.0:rpm failed: A required class was missing while executing de.dentrassi.maven:rpm:1.3.0:rpm: org/apache/commons/compress/compressors/zstandard/ZstdUtils
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>de.dentrassi.maven:rpm:1.3.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/c:/Entwicklung/.m2/repository/de/dentrassi/maven/rpm/1.3.0/rpm-1.3.0.jar
[ERROR] urls[1] = file:/c:/Entwicklung/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar
[ERROR] urls[2] = file:/c:/Entwicklung/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar
[ERROR] urls[3] = file:/c:/Entwicklung/.m2/repository/org/apache/maven/maven-builder-support/3.3.9/maven-builder-support-3.3.9.jar
[ERROR] urls[4] = file:/c:/Entwicklung/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
[ERROR] urls[5] = file:/c:/Entwicklung/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
[ERROR] urls[6] = file:/c:/Entwicklung/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[7] = file:/c:/Entwicklung/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[8] = file:/c:/Entwicklung/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2/org.eclipse.sisu.inject-0.3.2.jar
[ERROR] urls[9] = file:/c:/Entwicklung/.m2/repository/com/google/inject/guice/4.0/guice-4.0-no_aop.jar
[ERROR] urls[10] = file:/c:/Entwicklung/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[11] = file:/c:/Entwicklung/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
[ERROR] urls[12] = file:/c:/Entwicklung/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.6/plexus-component-annotations-1.6.jar
[ERROR] urls[13] = file:/c:/Entwicklung/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[14] = file:/c:/Entwicklung/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[15] = file:/c:/Entwicklung/.m2/repository/org/eclipse/packager/packager-rpm/0.16.0/packager-rpm-0.16.0.jar
[ERROR] urls[16] = file:/c:/Entwicklung/.m2/repository/org/bouncycastle/bcpg-jdk15on/1.63/bcpg-jdk15on-1.63.jar
[ERROR] urls[17] = file:/c:/Entwicklung/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.63/bcprov-jdk15on-1.63.jar
[ERROR] urls[18] = file:/c:/Entwicklung/.m2/repository/commons-codec/commons-codec/1.12/commons-codec-1.12.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------: org.apache.commons.compress.compressors.zstandard.ZstdUtils`

**Comment by ctron** [comment]
Hm, this is strange. I looks like you are missing the "commons-compress" dependency. Do you have a reproducer project that I could use for reproducing the issue?

**Comment by IT-Berater** [comment]
Hi, i have add dependency _commons-compress_ with includes ZstdUtils class to the project. The error is the same. I prepare the project next week.

**Comment by ctron** [comment]
Let me know when you have something, I will take a look.

**Comment by IT-Berater** [comment]
I update to 1.4.0. No bug. Good work. Thanks.
