### ISSUE TITLE
Suggestion: add an unpack goal to the plugin

### ISSUE THREAD

**Issue by frosiere** [ctron/rpm-builder#47]
In some situations, it would be very useful to have a goal to unpack the content of a given RPM.

This goal would simply extract the content of the rpm in a given directory.

**Comment by ctron** [comment]
Indeed, a nice idea. Could you contribute such a feature?

**Comment by dranuhl** [comment]
I have tried myself to write an unpack mojo, which would just unpack the RPM file content similar as a `rpm2cpio | cpio -idm` would do.

My code still needs some work:
- add more security checks on the file name(s) within the archive
- last modification time should be set if possible by underlying file system and user permissions
- add some integration test
- adapt my Java code style to existing project one :-)

Limitations of the current draft implementation:
- symbolic links would be ignored, even if the Java Nio FileSystem might support it
- only directories and regular files will be written (devices, pipes, networks, etc will be ignored)
- currently it would just always override any existing file
- file ownership (uid) will be ignored
- no file selection/filtering
- no directory stripping
- any RPM with "../" in the path would abort the extraction (avoid path traversal issues)
- Mojo marked as not thread safe as Apache Compress CPIO is not (should not be an issue, but just in case)

The Mojo would currently just have 2 parameters `rpm.file` and `rpm.unpackDirectory`.  It would not even require a project.

So stay tuned... PR will hopefully follow soon.

**Comment by dranuhl** [comment]
This has been fixed by #57 and so could probably be closed.

**Comment by ctron** [comment]
True, I will close it once I got it released.

Which might take a bit longer than expected, because I am busy with another release, that unfortunately requires a bit more attention at the moment than anticipated.

**Comment by ctron** [comment]
Many thanks @dranuhl for the contribution!
