### ISSUE TITLE
postrans missing

### ISSUE THREAD

**Issue by TomyLobo** [ctron/rpm-builder#48]
RPM's scriptlet execution order is the following (rpm -U, triggers not included)
1. `%pretrans` of the new package
2. `%pre` of the new package
3. (unpack new files)
4. `%post` of the new package
5. `%preun` of the old package
6. (delete old leftover files)
7. `%postun` of the old package
8. `%posttrans` of the new package

(See also https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#ordering)
If you naively stop your service in `%preun` and start it in `%post`, you end up with the service not running after an update, because `%preun` runs after `%post`.

Since the scriptlets get arguments depending on whether they're being upgraded, removed or freshly installed, a workaround is to place the start command into the install-only part of `%post` and into the upgrade-only part of `%postun`.
To be on the safe side, one would have to mirror this change for stopping the service, but that is usually not that critical.

But since `%preun` and `%postun` reside in the old package, while `%pre` and `%post` reside in the new package, you run into a problem if the commands needed to start the service ever need to be changed.

This is why we usually start our services in `%posttrans` instead of `%post`.
Recently, we decided we don't want to depend on the unportable rpm-maven-plugin anymore and wanted to switch to rpm-builder.
Unfortunately, rpm-builder does not support `%posttrans`.

Btw, I tried to develop a patch, but while I can build the plugin, I didn't have any luck building the packagedrone dependency, which also needs to be changed.

EDIT: I did some research, the tag IDs for `%pretrans` and `%posttrans` are as follows:
```
RPMTAG_PRETRANS = 1151,
RPMTAG_POSTTRANS = 1152,
RPMTAG_PRETRANSPROG = 1153,
RPMTAG_POSTTRANSPROG = 1154, 
```
Source: http://ftp.rpm.org/api/4.11.1/group__rpmtag.html

See also:
https://github.com/ctron/rpm-builder/pull/49
https://github.com/eclipse/packager/pull/11

**Comment by ctron** [comment]
Thank you for the issue. I absolutely agree that should be added.

> Btw, I tried to develop a patch, but while I can build the plugin, I didn't have any luck building the packagedrone dependency, which also needs to be changed.

That was the reason why the RPM bits got moved from "Eclipse Package Drone" to "Eclipse Packager" :grin: The most recent version of the maven plugin should already use those dependencies:

https://github.com/ctron/rpm-builder/blob/f2646190dc01a689136a1c1335e68d3c46dadb50/pom.xml#L94-L98

So everything you need should be in [eclipse/packager](https://github.com/eclipse/packager) now.

Let me know if you need some help. I would really appreciate a PR on this.

**Comment by TomyLobo** [comment]
oh, yeah i looked for the class name, thanks for the heads-up :)

**Comment by TomyLobo** [comment]
Builds fine, but I haven't tested it yet.

**Comment by ctron** [comment]
I just released version 1.5.0, which contains this. It might take a bit until it is available from maven central.

Maybe you can give it a try, then and then close this issue.

And thanks for the contribution!

**Comment by dranuhl** [comment]
The [scripts](https://ctron.github.io/rpm-builder/scripts.html) documentation page does not reflect the added support for "beforeTransaction" and "afterTransaction".

**Comment by ctron** [comment]
That is true, @dranuhl could you add that?

**Comment by dranuhl** [comment]
Have written the attached patch to update the documentation.
[0001-Issue-48-Update-script-documentation-to-reflect-1.5..patch.txt](https://github.com/ctron/rpm-builder/files/7561977/0001-Issue-48-Update-script-documentation-to-reflect-1.5.patch.txt)

**Comment by ctron** [comment]
Thanks for the patch! I haven't applied a patch for a long time :smile: 

I need to make a new release to publish the docs. So I will wait a bit to see of there are other changes. Should I forget about it, feel free to ping me.

**Comment by ctron** [comment]
As the functionality is actually implemented, I think I can close this issue.

**Comment by TomyLobo** [comment]
`git apply < 0001-Issue-48-Update-script-documentation-to-reflect-1.5..patch.txt`

**Comment by ctron** [comment]
> `git apply < 0001-Issue-48-Update-script-documentation-to-reflect-1.5..patch.txt`

Thanks for the tip! … I used `git am` however, as this command did also apply the commit information.

**Comment by TomyLobo** [comment]
even better!
Didn't actually look at the patch file :)
