### ISSUE TITLE
Signing is not ignored when skipSigning tag is used.

### ISSUE THREAD

**Issue by ugoud** [ctron/rpm-builder#5]
if ( !this.skipSigning && this.signature != null )
            {
                final SignatureProcessor signer = makeRsaSigner ( this.signature );
                if ( signer != null )
                {
                    builder.addSignatureProcessor ( signer );
                }
            }

is causing problem to skip signature in RpmMojo.java

**Comment by ctron** [comment]
I see. That should be an "or" instead.

I will make a fix tomorrow.

Thanks!

**Comment by ctron** [comment]
No .. that was wrong. Giving this a closer look I am not sure why this should be wrong.

**Comment by ugoud** [comment]
You are correct. I was using execution to define configuration. When I placed configuration under plugin this worked without any issues.

**Comment by ugoud** [comment]
Apologies for wasting your time.

**Comment by ctron** [comment]
No worries .. Boolean logic can be a beast :wink:
