### ISSUE TITLE
version parameter is ignored on SNAPSHOT builds

### ISSUE THREAD

**Issue by elkman** [ctron/rpm-builder#52]
Hi,

is there a good reason that in the case of a snapshot build, an explicitly defined version string via the `<version>` parameter is ignored?

In our case, the Maven version contains a hyphen (i.e. 2021-1.0.1-SNAPSHOT or 2021-1.0.1 for the release). 
The extra hyphen confuses `zypper` and a snapshot RPM like `foo-2021-1.0.1-0.202101020304.noarch.rpm` cannot be removed via:
`zypper remove foo` -> `Error: RPM failed: error: package foo-2021-1.0.1-0.202101020304.noarch is not installed`.

So we use something like 2021_1.0.1 derived from the project version and use it with the `<version>` parameter tag for our release packages, but always have to remove the shapshot RPMs with `rpm -e ...` by hand.

I have already created a patch to try this out, but would need to adjust the tests to submit a PR.
Additionally, a new parameter could be introduced to switch between old and new behavior if needed. 

Already thanks for feedback and all the great work that went into this plugin.

**Comment by ctron** [comment]
Thanks for the report. I didn't use this plugin for a while, so I may have missed a point.

Taking a look at the documentation (good I did that :grin: ) there is the following behavior (or at least, there should be):

> * The parameter “release” has no effect for “-SNAPSHOT” versions. Unless the parameter forceRelease is set to true, in which case the build will always fall back to the Non-SNAPSHOT behavior and use the release field as it is.

So I guess, in your case, you should be able to use `forceRelease=true` to get in full control of the version.

**Comment by elkman** [comment]
Sorry for the late response and thank you for your feedback. You are right, the implementation correctly follows the documentation.

But it is quite tedious in Maven to set `forceRelease=true` and in case of a snapshot build to derive and set a valid `<version>` and depending on the build type always set a correct `<release>`. That was the reason for my thoughts to use `<version>` also for snapshots.

So another suggestion would be to introduce a `<snapshotVersion>` analogous to `<snapshotReleasePrefix>` and `<snapshotBuildId>`. At least for my case, this would make configuration relatively easy.

If that sounds like a good idea, I would create a pull request for it.

**Comment by elkman** [comment]
Ok, I will see when I find some time. First I have to go on vacation for the next two weeks.
