### ISSUE TITLE
Symbolic Links are not added when <symbolicLinks>true</symbolicLinks> is set on collector

### ISSUE THREAD

**Issue by hochraldo** [ctron/rpm-builder#59]
Looking at the following code: 
https://github.com/ctron/rpm-builder/blob/fa22f571561dbd284eb81136709ada31a023fb10/src/main/java/de/dentrassi/rpm/builder/RpmMojo.java#L1191:L1197
to me it looks like the symlinks are not added to the rpm. There is a log output but nothing else.

**Comment by ctron** [comment]
Yes, that indeed looks suspicious. Could you investigate that further?

**Comment by hochraldo** [comment]
Sure, opened a PR with a possible solution. #62

**Comment by ctron** [comment]
I just released the fix as part of 1.7.1.

Thank you for fixing this!
