### ISSUE TITLE
Using <release> with other than "1" causes rpm-builder to produce 2 RPMs

### ISSUE THREAD

**Issue by watian** [ctron/rpm-builder#63]
Using <release> with other than "1" causes rpm-builder to produce 2 RPMs.
rpm-build will call both "(default-rpm)" and then "(default)", where the first will produce with release .1 and the second with my custom release value.
The problem is that CDCI tools to pick the output doesn't know which RPM file to chose.

Also the provided integration tests like test14-forcerelease does this.

**Comment by ctron** [comment]
Thanks for reporting this.

I just pushed a fix to this. The commit message should explain the cause in more detail. In a nutshell, the "test14" tests had been configured to actually run the build twice. It only showed up in the "forcerelease" test, as this created two different output file names.

Let me know if there is something unclear, so I can follow up.

**Comment by watian** [comment]
Thanks, looking at test14 now I understand how to configure my pom file as well, and now it generates just one RPM.
