### ISSUE TITLE
Ability to allow configuration changes on local files e.g. %config(noreplace) 

### ISSUE THREAD

**Issue by skarzhevskyy** [ctron/rpm-builder#7]
I believe handling RMP updated would be much easier with standard %config(noreplace) 

e.g. modified configuration files would remain on disk as is
and	edited in distribution file from the update in new file  .rpmnew.
(as it is right now with  %config  edited config file will end-up in .rpmsave)

---
Suggestion to have the parameter extended to minimize upgrade issues.
```
<configuration>true</configuration>
<configuration>false</configuration>
<configuration>noreplace</configuration>
```
as done in here: http://www.mojohaus.org/rpm-maven-plugin/map-params.html

**Comment by ctron** [comment]
Good point. So the first thing to do is to figure out how this will be represented in the binary rpm file.

**Comment by drecaise** [comment]
@ctron This is still open but I've just found out this has been implemented already. Shouldn't you close it? (  And out of context but a big thank you for your plugin! )

For who wants to try the syntax isn't as above you need two tags:
``
    <configuration>true</configuration>
    <noreplace>true</noreplace>
``

**Comment by ctron** [comment]
@drecaise You are right :grin: … There even is documentation for that: https://ctron.github.io/rpm-builder/payload_information.html … at least, a bit.

Thanks for reminding me!
