### ISSUE TITLE
Digest mismatch for RPM install with FIPS mode enabled

### ISSUE THREAD

**Issue by tksopra** [ctron/rpm-builder#70]
Installing RPM Packages generated with rpm-builder (v 1.9.0) fails when [fips mode](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/assembly_installing-a-rhel-8-system-with-fips-mode-enabled_security-hardening) is enabled (tested with AlmaLinux 8):

`rpm -ihv test-1-1.noarch.rpm`

`Verifying...                 ################################# [100%]`
`Preparing...                 ################################# [100%]`
`Updating / installing...`
`   1:test-1-1                ################################# [100%]`
`error: unpacking of archive failed on file [...]: cpio: Digest mismatch`
`error: test-1-1.noarch: install failed`

The reason is that fips expects the file digest to be atleast a sha256:

`rpm -ihv --nofiledigest test-1-1.noarch.rpm`

succeeds (but is not an always an option depending on security standards/guidelines for the target system).

To see the file digest use:

`rpm -q --dump --scripts -p test-1-1.noarch.rpm`

-> [...] 166 1673000915 **af90be808ed1abd48b3c0b5026056903** 0100644 root root 0 0 0 X

The package can be fixed by running rpmrebuild (%_source_filedigest_algorithm 8 + %_binary_filedigest_algorithm 8) - but this depends on the rpm-builder which i want to avoid (otherwise i could use [rpm-maven-plugin](https://www.mojohaus.org/rpm-maven-plugin/) to generate the rpm in the first place):

`rpmrebuild -p test-1-1.noarch.rpm`
`rpm -q --dump --scripts -p rpmbuild/RPMS/noarch/test-1-1.noarch.rpm`

-> [...] 166 1673363869 **e988af6edb29fc324dfd847607b9fe9991c8f6476d23f99eed60a2d0040259dd** 0100644 root root 0 0 0 X

So to fix this properly the rpm-builder would need to generate the file digest with the sha256 algorithm or (probably even better) allow the algorithm to be specified via configuration.

**Comment by ctron** [comment]
In general I agree, this should be supported out of the box.

As always with signatures, checksum, and RPM headers, this needs a bit more understanding on what to do exactly. :)

There is already a sha256 digest, but of the header only. There is also a digest of header + payload, but this rarely used. Then there is the digest of the files themselves, and I think this is the one you are looking for.

This is controlled by the `BuilderOptions`, which default to `MD5` indeed:

https://github.com/eclipse/packager/blob/d002b447d309f1ea093023a0ecef4092a3928182/rpm/src/main/java/org/eclipse/packager/rpm/build/BuilderOptions.java#L46

So ideally, this should be a simple change to allow overriding this, defaulting to e.g. SHA-512?

**Comment by tksopra** [comment]
> So ideally, this should be a simple change to allow overriding this, defaulting to e.g. SHA-512?

Yes - this should fix the problem (atleast up until fips considers sha512 insecure)

**Comment by ctron** [comment]
> If there is a way define/overwrite this value in my pom.xml i will test it (haven't found anything in the documentation - but might have overlooked it)

Not yet :) … I am working on this right now. I might have a PR ready in a bit. It would be great if you could test it (once it is ready) to see if this fixes the issue for you.

I am tempted however to go with SHA-256, as I saw this being used in fedora 36. Still, you would be able to override this SHA-512.

**Comment by ctron** [comment]
Maybe a first step could be to take one of the RPMs created by the integration tests of the RPM builder and try to install it on a virtual machine with the same configuration.

If that helps, I can upload an RPM from a test to this issue.

If that works, I would say chances are good it would work in your other case too.

**Comment by tksopra** [comment]
> Maybe a first step could be to take one of the RPMs created by the integration tests of the RPM builder and try to install it on a virtual machine with the same configuration.
> 
> If that helps, I can upload an RPM from a test to this issue.

This would be great - i should be able to test that rather quickly

**Comment by ctron** [comment]
The integration tests and docs are updated too. From my perspective this is good to go. But I will wait on your feedback before doing a release.

**Comment by tksopra** [comment]
> My expectation would be, that the `test18-md5.rpm` does not work, but the `test18-default.rpm` does.

As expected:

`rpm -ihv test18-md5.rpm`
>Verifying...                          ################################# [100%]
>Preparing...                          ################################# [100%]
>Updating / installing...
 >  1:test18-file-digest-md5-1.0.0-0.20################################# [100%]
>error: unpacking of archive failed on file /etc/test.txt;63be9150: cpio: Digest mismatch
>error: test18-file-digest-md5-1.0.0-0.200901011100.noarch: install failed

`rpm -ihv test18-sha256.rpm`
>Verifying...                          ################################# [100%]
>Preparing...                          ################################# [100%]
>Updating / installing...
 >  1:test18-file-digest-md5-1.0.0-0.20################################# [100%]

**Comment by ctron** [comment]
Cool, I will prepare a release then! Thanks for testing!

**Comment by ctron** [comment]
I released version 1.10.0 of the plugin, which contains this change. It might take a bit longer until it is visible on maven central.
