### ISSUE TITLE
Do RPM Builder supports RPM macros?

### ISSUE THREAD

**Issue by ArtRac** [ctron/rpm-builder#84]
Do this tool supports RPM macros?
https://rpm-software-management.github.io/rpm/manual/macros.html

**Comment by ctron** [comment]
No, it does not. However, I also don't see a need for it.

To my understanding, macros mainly expand content in the "spec" file. The spec file is the build-file for an RPM. However, in this case, Maven is the build tool, and POM its build file. And, Maven has it's tools for injecting content into the Pom file.

**Comment by ArtRac** [comment]
Thank you @ctron for your answer.
